export const GET_CATS = 'GET_CATS';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILED = 'GET_CATS_FAILED';

export const SEARCH_CATS = "SEARCH_CATS";
export const SEARCH_CATS_SUCCESS = "SEARCH_CATS_SUCCESS";

export const PAGINATE_CATS = "PAGINATE_CATS";
export const PAGINATE_CATS_SUCCESS = "PAGINATE_CATS_SUCCESS"; 