export const GET_CATS = 'GET_CATS';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILED = 'GET_CATS_FAILED';
export const FILTER_CATS = "FILTER_CATS"
export const FILTER_CATS_SUCCESS = "FILTER_CATS_SUCCESS"
